export const AUTH_SET_USER = "AUTH_SET_USER"
export const AUTH_SET_PERMISSION = "AUTH_SET_PERMISSION"
export const AUTH_RESET_PERMISSION = "AUTH_RESET_PERMISSION"

export const DIALOG_SET_DIALOG = "DIALOG_SET_DIALOG"

export const SNACKBAR_OPEN_SNACKBAR = "SNACKBAR_OPEN_SNACKBAR"
export const SNACKBAR_CLOSE_SNACKBAR = "SNACKBAR_CLOSE_SNACKBAR"

export const CONFIG_SET_CONFIG = "CONFIG_SET_CONFIG"

export const USERS_SET_LIST = "USERS_SET_LIST"
export const USERS_SET_ROLE_OPTIONS = "USERS_SET_ROLE_OPTIONS"
export const USERS_SET_USER_UNIQUE = "USERS_SET_USER_UNIQUE"
